
#' View readout of projection evaluation metric values
#'
#' Shows a formatted table with values of projection (de-noising/dimension-reduction) evaluation metrics for a chosen subpipeline of a \code{Benchmark} object.
#' If you are running R in *RStudio*, the output should show up in the *Viewer* pane.
#' Otherwise, you will probably see the ouput pop up in a new window/tab of your web browser.
#'
#' @param benchmark an object of class \code{Benchmark}, as generated by the constructor \code{Benchmark} and evaluated using \code{Evaluate.Benchmark}
#' @param idx.subpipeline integer value: index of sub-pipeline that includes a projection step
#'
#' @export
ShowReadout_Projection <- function(
  benchmark,
  idx.subpipeline
) {
  
  .PlotProjection.ValidityChecks(environment())
  
  vals <- GetProjectionScoringTable(benchmark, idx.subpipeline)
  
  kableExtra::kable_styling(kableExtra::kbl(vals, align = 'r'))
}

#' View readout of clustering evaluation metric values
#'
#' Shows a formatted table with values of clustering evaluation metrics for a chosen subpipeline of a \code{Benchmark} object.
#' If you are running R in *RStudio*, the output should show up in the *Viewer* pane.
#' Otherwise, you will probably see the ouput pop up in a new window/tab of your web browser.
#'
#' @param benchmark an object of class \code{Benchmark}, as generated by the constructor \code{Benchmark} and evaluated using \code{Evaluate.Benchmark}
#' @param idx.subpipeline integer value: index of sub-pipeline that includes a clustering step
#'
#' @export
ShowReadout_Clustering <- function(
  benchmark,
  idx.subpipeline
) {
  
  vals <- GetClusteringScoringTable(benchmark, idx.subpipeline)
  
  kableExtra::kable_styling(kableExtra::kbl(vals, align = 'r'))
}
